apiVersion: 1

prune: true

datasources:
  - name: LibraryDeskSense InfluxDB
    uid: library-desksense-influx
    type: influxdb
    access: proxy
    url: ${INFLUX_URL}
    isDefault: true
    editable: true
    jsonData:
      version: Flux
      organization: ${INFLUX_ORG}
      defaultBucket: ${INFLUX_BUCKET}
      tlsSkipVerify: true
    secureJsonData:
      token: ${INFLUX_TOKEN}
